- hosts: localhost
  connection: local
  vars:
    


  tasks:
        
    -   name: Fetch GitLab Role
        git:
            repo: https://ro:vKA_9cGeQbxdHCD5xUr8@pwslab.org/ansible/gitlab-playbook.git
            dest: /root/.ansible/roles/pwslab.gitlab
            version: master
            force: yes

    -   pause:
            prompt: "Please enter your Domain Name:"
            echo: yes
        register: domain_name_result

    -   pause:
            prompt: "Please enter your Email ID:"
            echo: yes
        register: email_id_result

    -   set_fact:
            gitlab_domain: "{{ domain_name_result.user_input }}"
            contact_emails: "{{ email_id_result.user_input }}"
            gitlab_registry_external_url: "{{ domain_name_result.user_input }}"

    -   name: Installing GitLab
        include_role:
            name: pwslab.gitlab